services:
  rdcli:
    build:
      context: .
      dockerfile: Dockerfile
    image: robotics-deployment:cli
    container_name: rdcli
    volumes:
      - ./rdcli:/opt/rdcli
    command: ["sleep", "infinity"]