services:
  rdcli:
    build:
      context: .
      dockerfile: Dockerfile
    image: robotics-deployment:cli
    container_name: rdcli
    volumes:
      - ./rdcli:/opt/rdcli
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["sleep", "infinity"]