[package]
name = "rdcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "^0.16"
tokio = { version = "^1.0", features = ["full"] }
serde_json = { version = "^1.0"}