name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: enable qemu
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Login ghcr.io
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull containers
      run: docker-compose -f "docker-compose.yml" pull

    - name: Pull containers
      run: docker-compose -f "docker-compose.yml" up -d

    - name: Build amd64
      run: docker exec rdcli-amd64 cargo build --release --target x86_64-unknown-linux-gnu

    - name: Strip amd64
      run: docker exec rdcli-amd64 x86_64-linux-gnu-strip target/x86_64-unknown-linux-gnu/release/rdcli

    - name: Build arm64
      run: docker exec rdcli-arm64 cargo build --release --target aarch64-unknown-linux-gnu

    - name: Strip arm64
      run: docker exec rdcli-arm64 aarch64-linux-gnu-strip target/aarch64-unknown-linux-gnu/release/rdcli

    - name: Stop Docker Compose services
      run: docker-compose -f docker-compose.yml down

    - uses: actions/upload-artifact@v3
      with:
        name: rdcli-x86_64
        path: |
          rdcli/target/x86_64-unknown-linux-gnu/release/rdcli

    - uses: actions/upload-artifact@v3
      with:
          name: rdcli-aarch64
          path: |
            rdcli/target/aarch64-unknown-linux-gnu/release/rdcli